name: Frontend CI

on:
  push:
    paths:
      - 'frontend/**'
    branches: [main]
  pull_request:
    paths:
      - 'frontend/**'
    branches: [main]

jobs:
  lint-and-test:
    name: Lint & Test Frontend
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js 18
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: |
          cd frontend
          npm ci

      - name: Run ESLint
        run: |
          cd frontend
          npx eslint src --max-warnings=0

      - name: Run unit tests
        run: |
          cd frontend
          npm test -- --watchAll=false
